# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo: 
        image: mvertes/alpine-mongo
        ports:
          - 27018:27017
        options: --health-cmd='mongo --eval "db.adminCommand('ping')" || exit 1' --health-interval=10s --health-timeout=5s --health-retries=5

      rabbitmq:
        image: rabbitmq:alpine
        ports:
          - 5672:5672
        options: --health-cmd='rabbitmqctl status' --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies for Products service
          working-directory: ./products
          run: npm install

      - name: Install dependencies for Shopping service
        working-directory: ./shopping
        run: npm install

      - name: Install dependencies for Customer service
        working-directory: ./customer
        run: npm install

      - name: Run tests for Products service
        working-directory: ./products
        run: npm test

      - name: Run tests for Shopping service
        working-directory: ./shopping
        run: npm test

      - name: Run tests for Customer service
        working-directory: ./customer
        run: npm test

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Run Docker containers
        run: docker-compose -f docker-compose.yml up -d
